### ISSUE TITLE
Problems with Rustfoil

### ISSUE THREAD

**Issue by imsl0wer** [DevYukine/rustfoil#3]
First I wanna ask if an ARM version is planned. I wanna run it on my pi4.

2nd everything worked before but when try generating an index right now it alway's gives me this error:

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BadRequest(ErrorResponse { error: ServerError { errors: [ServerMessage { domain: "global", reason: "backendError", message: "Backend Error", location_type: None, location: None }], code: 500, message: "Backend Error" } })', src\main.rs:375:22`

**Comment by imsl0wer** [comment]
fixed for now

**Comment by DevYukine** [comment]
For reference, this was caused by a Google Drive Internet Server Error, Rustfoil currently does not retry Google Drive exceptions
