### ISSUE TITLE
Fails to create index

### ISSUE THREAD

**Issue by adh1310** [DevYukine/rustfoil#7]
When running on Ubuntu 18.04, the application fails to create the index.tfl properly, it creates it as a directory and not a file. This causes the application to error out after scanning. This is using the compiled version available in the workflows as well as a self-compiled version from the source.

`[Info] Parsed 19888 file(s)
[Info] Generated index successfully
Error: Is a directory (os error 21)`

If I manually create the file before running the script, it errors out with the following:

`[Info] Parsed 19888 file(s)
[Info] Generated index successfully
Error: File exists (os error 17)`

**Comment by DevYukine** [comment]
Hey, thanks for reporting this, in order to get some more debug information on this can you give me the complete command you run to generate that index (feel free to [REDACTED] your google ids tho).

Also can you make sure to run latest stable and latest nightly and try to see if this already got fixed in a newer commit?

**Comment by adh1310** [comment]
`./rustfoil --success "Welcome!" --upload-folder-id [REDACT] --share-index --output-path shop.tfl [REDACT]`

I've run it on both v0.3.0 and on the nightly from commit 488657a. I've also tried the command with the --compressiona and --encrypt commands (with --public-key) and same errors.

Running TinGen.py from exHumer works properly though without error.

**Comment by C0nsp1racy** [comment]
Running into the same problem on the nighly mentioned above running the x64 on windows 10.
Running Rustfoil with an old .tfl present causes an os error 183 (can't create file that already exists), removing the .tfl outputs a folder with the same name and an os error 5 (acces denied).

Executing the following command:
C:\Rustfoil\rustfoil.exe  --credentials credentials\stash1.json --token token\token1.json --public-key public.key --output-path StealthShop.tfl --share-folders --share-index --upload-folder-id [redacted] --theme-whitelist [redacted] --theme-error "[redacted]" --success "Welcome!" 

Stable version 0.3.0 does not error out for me.

**Comment by DevYukine** [comment]
Hey, i just pushed a fix with f636e82ae5821f0388f1ebbae0f54fd26c63b829, can you try and report if that fixes the issues for you?

**Comment by C0nsp1racy** [comment]
Yukine, newest build works like a charm. Only side note is if people had a directore as output on the previous build, one should remove that directory to regenerate a index without issues.

**Comment by DevYukine** [comment]
Fixed in f636e82ae5821f0388f1ebbae0f54fd26c63b829
